name: Build and push image

on:
  push:
    branches:
      - main
      - develop

    paths:
      - "src/**"
      - "dockerfile"
      - "requirements.txt"
      
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ci.yaml
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: test
    env:
      USERNAME: ${{ secrets.docker_username }}
      PASSWORD: ${{ secrets.docker_password }}
      TAG: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker hub
      run: docker login -u ${USERNAME} -p ${PASSWORD}
    - name: Build the Docker image
      run: docker build . --tag ${USERNAME}/azubichat:${TAG}
    - name: Push image
      run: docker push ${USERNAME}/azubichat:${TAG}
