name: Test and Build

on:
  pull_request:
    branches: ["develop", "main"]

  workflow_dispatch:

jobs:
  test:
    name: Run python unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover tests
  
  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - name: Build image
        run: docker build -t ${DOCKER_USERNAME}/azubichatbot:${TAG_NAME} ./
      
      - name: Push image
        run: docker push ${DOCKER_USERNAME}/azubichatbot:${TAG_NAME}
      



